"use client";

import React, { useState, useEffect } from "react";
import { FileBarChart2, Download, Eye } from "lucide-react";
import {
  reportService,
  ReportActivity,
  ReportSummary,
} from "@/services/reportService";

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportActivity[]>([]);
  const [summary, setSummary] = useState<ReportSummary>({
    totalReports: 0,
    totalDownloads: 0,
  });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  // ✅ API CALL: reports overview fetch karna (summary + recent activity)
  const fetchReports = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await reportService.getOverview();
      setSummary(res.data.summary);
      setReports(res.data.recentActivity || []);
    } catch (err) {
      console.error("Reports overview fetch error:", err);
      setError("Reports could not be loaded. Please retry.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  // ✅ API CALL: report download karna


  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh]">
        <div className="w-16 h-16 border-4 border-gray-200 border-t-[#18A096] rounded-full animate-spin"></div>
        <p className="mt-4 text-gray-500 text-sm font-medium">Loading reports...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Top Header Banner */}
      <div className="bg-gradient-to-r from-[#18A096] to-[#12544F] rounded-2xl p-6 text-white shadow-md">
        <h1 className="text-2xl font-bold">Reports</h1>
      </div>

      {error && (
        <div className="p-3 bg-red-50 text-red-600 rounded-xl text-sm font-medium">
          {error}
        </div>
      )}

      {/* Stat cards - ✅ ab summary API se aa raha hai */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm flex items-center gap-5">
          <div className="w-14 h-14 rounded-full bg-[#62FFF3]/20 flex items-center justify-center shrink-0">
            <FileBarChart2 className="w-6 h-6 text-[#12544F]" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-gray-900">
              Total Reports
            </h3>
            <p className="text-3xl font-bold text-gray-900 mt-1">
              {summary.totalReports}
            </p>
            <p className="text-sm text-gray-400">All Time</p>
          </div>
        </div>

        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm flex items-center gap-5">
          <div className="w-14 h-14 rounded-full bg-[#18A096]/10 flex items-center justify-center shrink-0">
            <Download className="w-6 h-6 text-[#18A096]" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-gray-900">
              Downloads
            </h3>
            <p className="text-3xl font-bold text-gray-900 mt-1">
              {summary.totalDownloads}
            </p>
            <p className="text-sm text-gray-400">All time</p>
          </div>
        </div>
      </div>

      {/* Recent reports table */}
      <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
        <h2 className="text-base font-bold text-gray-900 mb-5">
          Recent Reports
        </h2>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="text-xs font-semibold text-gray-400 uppercase tracking-wide border-b border-gray-100">
                <th className="py-3 pr-4">Report Name</th>
                <th className="py-3 pr-4">Date Range</th>
                <th className="py-3 pr-4">Generated On</th>
                <th className="py-3 pr-4">Generated By</th>
                <th className="py-3 pr-4">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr
                  key={report.id}
                  className="border-b border-gray-50 hover:bg-gray-50/60 transition-colors"
                >
                  <td className="py-4 pr-4 text-sm font-medium text-gray-900">
                    {report.name}
                  </td>
                  <td className="py-4 pr-4 text-sm text-gray-500">
                    {report.dateRange}
                  </td>
                  <td className="py-4 pr-4 text-sm text-gray-500">
                    {report.generatedOn}
                  </td>
                  <td className="py-4 pr-4 text-sm text-gray-500">
                    {report.generatedBy}
                  </td>
                  <td className="py-4 pr-4">
                    <div className="flex items-center gap-2">
                      <button
                        title="View"
                        className="w-7 h-7 rounded-full bg-[#18A096]/10 flex items-center justify-center text-[#18A096] hover:bg-[#18A096]/20 transition-colors"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </button>
                      <button
                        title="Download"
                        className="w-7 h-7 rounded-full bg-gray-100 flex items-center justify-center text-gray-500 hover:bg-gray-200 transition-colors disabled:opacity-50"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}

              {reports.length === 0 && (
                <tr>
                  <td
                    colSpan={5}
                    className="py-10 text-center text-sm text-gray-400"
                  >
                    No reports found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}